export function createPdfFixture() {
  const names = [
    "Disciplina y rutina de visita",
    "Técnica de negociación",
    "Manejo de objeciones",
    "Visibilidad y exhibición",
    "Gestión del tiempo y servicio",
    "Adaptabilidad en calle",
    "Resiliencia y presión",
    "Registro oportuno",
    "Calidad de la información",
    "Adopción tecnológica",
    "Trabajo en equipo",
    "Honestidad",
    "Respeto",
    "Pasión por el servicio",
  ];

  return {
    generatedAt: "2026-07-28T23:00:00.000Z",
    evaluationId: "EV-2026-001",
    profile: {
      name: "María Rodríguez",
      id: "10203040",
      zone: "Geográfico Tierra",
      route: "RT-042",
      period: "Enero - Junio 2026",
      date: "28/07/2026",
      boss: "Carlos Méndez",
      tenure: "2 años",
    },
    summary: {
      complete: true,
      completeness: 100,
      score100: 87.42,
      score5: 4.37,
      category: "Destacado",
      completedKpis: 7,
      completedBehaviors: 14,
    },
    blocks: {
      kpis: { points: 26.4, maximum: 30 },
      competencies: { points: 25.8, maximum: 30 },
      attitudes: { points: 26.1, maximum: 30 },
      values: { points: 9.12, maximum: 10 },
    },
    kpis: [
      "Presupuesto de ventas",
      "Cobertura efectiva de ruta",
      "Apertura de nuevos clientes",
      "Distribución de marcas foco",
      "Distribución de portafolio",
      "Ejecución impecable en PDV",
      "Control de activos",
    ].map((name, index) => ({
      code: `KPI-0${index + 1}`,
      name,
      weight: [0.08, 0.05, 0.04, 0.04, 0.03, 0.04, 0.02][index],
      actual: String(95 + index * 3),
      target: "100",
      compliance: (95 + index * 3) / 100,
      rating: index < 2 ? 3 : 4,
    })),
    behaviors: names.map((name, index) => ({
      block: index < 5 ? "Competencias" : index < 10 ? "Actitudinal" : "Valores",
      code: `CO-${String(index + 1).padStart(2, "0")}`,
      name,
      sources: { auto: "4", jefe: "4", pares: "5", clientes: "4" },
      weightedScore: 4.2,
    })),
    feedback: {
      start: "Usar el tablero de oportunidades antes de iniciar cada ruta.",
      stop: "Postergar el registro de novedades al cierre de la jornada.",
      continue: "Mantener la cercanía y el seguimiento oportuno a los tenderos.",
      strengths: "Disciplina comercial, orientación al servicio y conocimiento del portafolio.",
      gaps: "Profundizar el análisis de datos y la planeación de clientes prioritarios.",
      action: "Realizar revisión quincenal con el supervisor durante 90 días. Indicador: cobertura efectiva superior al 95%.",
    },
  };
}
